# Generated by Django 4.0.4 on 2022-05-05 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='author',
        ),
    ]
